--- #YAML:1.0
name:                Glib-Ex-ObjectBits
version:             3
abstract:            Helpers for Glib objects.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Glib:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
recommends:
    Test::Pod: 1.00
no_index:
    directory:
        - devel
resources:
    homepage: http://www.geocities.com/user42_kevin/glib-ex-objectbits/index.html
    license: http://www.gnu.org/licenses/#GPL
